### ISSUE TITLE
Not Supporting Swedish Currency "SEK"

### ISSUE THREAD

**Issue by geekyRJ** [bambora/checkout-sdk-android#1]
checkoutOrder.put("amount", 375);
checkoutOrder.put("currency", "EUR");

when i chenge from EUR to SEK. it gives error. 

checkoutOrder.put("amount", 375);
checkoutOrder.put("currency", "SEK");

"The requested payment type or currency is not supported. this can be caused by missing agreement for the used currency."

**Comment by mohsinnaeem21** [comment]
@geekyRJ did you find any solutions? I am encountering the same issue.

**Comment by BaseMax** [comment]
This is supported and not a problem.
I tried and works as well. (But not in android, I test in web) :+1:

**Comment by storkie** [comment]
If you experience this issue, please contact our support team who will help configure your account to support multiple currencies.
They can be reached at ecom.integration@bambora.com

**Comment by trungnb-vvt** [comment]
Anyone found a solution? i have the same problem.
