### ISSUE TITLE
BuildConfig.VERSION_NAME is not being generated, introduced in AGP 4.1+

### ISSUE THREAD

**Issue by TouchBoarder** [bambora/checkout-sdk-android#2]
The `BuildConfig.VERSION_NAME` is no longer generated as a build config field after upgrading to Android Gradle Plugin 4.1+ 

**Why?** https://issuetracker.google.com/issues/158695880#comment15

This causes a issue with the `BamboraCheckout.java` class
```
    /**
     * Initilize the paymentwindow
     * @return BamboraCheckout
     */
    @SuppressLint("SetJavaScriptEnabled")
    public BamboraCheckout initialize()
    {
        String versionName = "CheckoutSDKAndroid/" + BuildConfig.VERSION_NAME;
        String checkoutOptions = String.format("{version:%1s}", versionName);
```

Workaround: Create a new unique build config field

build.gradle
```
    defaultConfig {
        ...
        buildConfigField 'String', 'BAMBORA_CHECKOUT_SDK_VERSION_NAME', "\"1.0.1\""
    }
```
BamboraCheckout.java
` String versionName = "CheckoutSDKAndroid/" + BuildConfig.BAMBORA_CHECKOUT_SDK_VERSION_NAME;`

**Comment by storkie** [comment]
Thanks for sharing, @TouchBoarder
We've released a version 2 of the SDK so I'll close this.
