### ISSUE TITLE
How to import this in android (not in kotlin)

### ISSUE THREAD

**Issue by Rohitsachdeva** [bambora/checkout-sdk-android#4]
I want to import same project in android, how can i do it. while i am doing it i am facing multiple issues

**Comment by Worldline-Bambora-Checkout-support** [comment]
Hello Rohit,

Can you explain a bit more on what you are trying to do? Are you trying to import the project through Gradle?
Also, could you share some more details about the issues you are running into? Do you have logs for example?

**Comment by Rohitsachdeva** [comment]
implementation "com.bambora.checkout:androidsdk:2.0.2"

in app level gradle.

Can't determine type for tag '<macro name="m3_comp_assist_chip_container_shape">?attr/shapeAppearanceCornerSmall</macro>'

![image](https://github.com/bambora/checkout-sdk-android/assets/2804034/5f10698e-7be2-4c31-88f5-f41829224b44)

**Comment by Worldline-Bambora-Checkout-support** [comment]
Hello Rohit,

From your screenshot the issue appears to be in the material library. Can you confirm that the error is caused by our library by temporarily removing it as an import and verifying that your project builds?

Also, could you share your 'build.gradle' (be careful to remove potentially sensitive details) so that we can attempt to reproduce the issue? Thank you.

**Comment by Rohitsachdeva** [comment]
I tried by removing material library but same issue.

**Comment by Worldline-Bambora-Checkout-support** [comment]
Hello Rohit,
 
After some investigation we have managed to reproduce and fix your issue. We've come to the conclusion that this has nothing to do with our SDK, but with the `com.google.android.material:material` version that you are using in your project. From material version 1.7.0 and up, there are new minimum requirements that your app should comply to. You can find these [here](https://github.com/material-components/material-components-android/releases/tag/1.7.0). 
 
Please keep in mind that you might need to invalidate the cache of your Android Studio before you see any effect.

**Comment by Rohitsachdeva** [comment]
I have removed material design implementation from gradle. but facing same issue

![image](https://github.com/bambora/checkout-sdk-android/assets/2804034/d74db853-86a7-49d8-adb6-46809106965d)


    apply plugin: 'com.android.application'
    apply plugin: 'com.google.firebase.crashlytics'

    android {
      compileSdkVersion rootProject.ext.compileSdkVersion
      buildToolsVersion rootProject.ext.buildToolsVersion
      defaultConfig {
        applicationId "com.caindus.ticketzapper"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 3
        versionName "1.2"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true
        multiDexEnabled true

    }
    buildTypes {
        debug {
            buildConfigField("boolean", "Authorization", "false")
        }

        release {
            minifyEnabled false
            buildConfigField("boolean", "Authorization", "false")

        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    dataBinding {
        enabled = true
    }

    packagingOptions{
        exclude("META-INF/jersey-module-version")
        exclude 'lib/getLibs.ps1'
        exclude 'lib/getLibs.sh'
        exclude 'lib/gson-2.2.2.jar'
        exclude 'lib/signalr-client-sdk.jar'
        exclude 'lib/signalr-client-sdk-android.jar'
    }
     }

      dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation project(':scanlibrary')
    implementation project(':imagestopdf')
    implementation 'com.microsoft.identity.client:msal:2.2.3'

    // android support libraries
    implementation "androidx.appcompat:appcompat:$rootProject.supportLibraryVersion"
    implementation "androidx.recyclerview:recyclerview:$rootProject.recyclerViewVersion"
    implementation "androidx.cardview:cardview:$rootProject.cardViewVersion"
   
    implementation "androidx.vectordrawable:vectordrawable:$rootProject.vectorDrawableVersion"
    implementation "androidx.vectordrawable:vectordrawable-animated:$rootProject.animatedVectorDrawableVersion"
    implementation "androidx.constraintlayout:constraintlayout:$rootProject.constraintLayoutVersion"
    implementation 'com.android.support:multidex:1.0.3'


    // network
    implementation "com.amitshekhar.android:rx2-android-networking:$rootProject.rx2FastAndroidNetworking"

    // database
    implementation "androidx.room:room-rxjava2:$rootProject.roomDatabaseVersion"
    annotationProcessor "androidx.room:room-compiler:$rootProject.roomDatabaseVersion"

    // font
    implementation "io.github.inflationx:calligraphy3:3.1.1"
    implementation "io.github.inflationx:viewpump:2.0.3"
    implementation 'commons-io:commons-io:2.5'

    // image
    implementation "com.github.bumptech.glide:glide:$rootProject.glideVersion"

    // parser
    implementation "com.google.code.gson:gson:$rootProject.gsonVersion"

    // debug database
    debugImplementation "com.amitshekhar.android:debug-db:$rootProject.debugDBVersion"

    // dependency injection
    implementation "com.google.dagger:dagger:$rootProject.dagger2Version"
    annotationProcessor "com.google.dagger:dagger-compiler:$rootProject.dagger2Version"
    annotationProcessor "com.google.dagger:dagger-android-processor:$rootProject.dagger2Version"
    implementation "com.google.dagger:dagger-android-support:$rootProject.dagger2Version"

    // reactive
    implementation "io.reactivex.rxjava2:rxjava:$rootProject.rxjava2Version"
    implementation "io.reactivex.rxjava2:rxandroid:$rootProject.rxandroidVersion"

    // swipe view
    implementation "com.mindorks:placeholderview:$rootProject.placeholderviewVersion"

    // logger
    implementation "com.jakewharton.timber:timber:$rootProject.timberVersion"

    // dependencies for local unit tests
    testImplementation "junit:junit:$rootProject.ext.junitVersion"
    testImplementation "org.mockito:mockito-core:$rootProject.mockitoVersion"
    testAnnotationProcessor "com.google.dagger:dagger-compiler:$rootProject.dagger2Version"

    // UI Testing
    androidTestImplementation "androidx.test.espresso:espresso-core:$rootProject.espressoVersion"
    androidTestImplementation "androidx.test.espresso:espresso-intents:$rootProject.espressoVersion"
    androidTestImplementation "org.mockito:mockito-core:$rootProject.mockitoVersion"
    androidTestAnnotationProcessor "com.google.dagger:dagger-compiler:$rootProject.dagger2Version"

    // view model
    implementation "androidx.lifecycle:lifecycle-extensions:$rootProject.lifecycleVersion"
    annotationProcessor "androidx.lifecycle:lifecycle-compiler:$rootProject.lifecycleVersion"

    // bigkoo weheel view
    implementation "com.contrarywind:Android-PickerView:$rootProject.bigkooWheelViewVersion"

    //snackbar
    implementation "io.github.tonnyl:light:$rootProject.snaackBarVersion"

    implementation("com.google.firebase:firebase-crashlytics:18.6.0")
    implementation("com.google.firebase:firebase-analytics:21.5.0")

    //ContraintLayout
    implementation "com.android.support.constraint:constraint-layout:$rootProject.contraintLayout"
    implementation 'com.ogaclejapan.smarttablayout:library:2.0.0@aar'
    implementation 'com.ogaclejapan.smarttablayout:utils-v4:2.0.0@aar'

    // google Login

    implementation "com.google.android.gms:play-services-auth:$rootProject.gogoleLogin"


    // runtime permissions
    implementation 'com.karumi:dexter:6.0.0'
    implementation 'com.wdullaer:materialdatetimepicker:4.2.3'

    implementation 'com.google.firebase:firebase-core:17.4.0'
    implementation 'com.google.firebase:firebase-messaging:20.1.6'

    implementation 'com.google.android.play:core:1.8.0'

    implementation 'com.github.dhaval2404:imagepicker:2.1'


    implementation "androidx.activity:activity-ktx:1.4.0"
    implementation "androidx.fragment:fragment-ktx:1.4.1"

    implementation 'com.android.volley:volley:1.2.1'

    implementation "com.bambora.checkout:androidsdk:2.0.2"
    }

   configurations.all {
    resolutionStrategy.force 'com.google.code.findbugs:jsr305:1.3.9'
     }

   apply plugin: 'com.google.gms.google-services'

**Comment by Worldline-Bambora-Checkout-support** [comment]
Hello Rohit,

Did you verify your Android Studio version, and other requirements in the documentation that we shared with you for material v1.7.0? According to our reproduction, your issue is most likely caused by one of those requirements not being met.
Also, we noticed that you opened another issue titled "My app is as per these instructions and still same issue which i posted", but later closed it with the comment "i fixed". Can you confirm whether you referred to this issue, and is your build issue resolved?

Kind regards, and thank you!
